### ISSUE TITLE
[SCM-837] SVNEXE Provider: enable setting env, path, or full path to svn.exe

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-scm#1068]
**[David Akehurst](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dhakehurst)** opened **[SCM-837](https://issues.apache.org/jira/browse/SCM-837?redirect=false)** and commented

We need to use the svn exe provider in a context where the environment path does not contain svn.exe.

We can programatically determine the location of svn.exe and need to pass this location into the provider so that either,
- we can alter the path env variable used by the provider when running a command line (preferred)
- or, tell the provider the full path to the svn.exe to use,

---

**Affects:** 1.9.5

**Issue Links:**
- [SCM-858](https://issues.apache.org/jira/browse/SCM-858) Configuration for git path

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Would be a suitable to add a configuration [here](http://maven.apache.org/scm/maven-scm-providers/maven-scm-providers-svn/maven-scm-provider-svn-commons/svn-settings.html)?

**Comment by jira-importer** [comment]
**[David Akehurst](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dhakehurst)** commented

No I am afraid that won't work in our situation.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

What type of solution would you provide which would work w/o rewriting the entire code?

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

No answer to question for more than 16 months.

**Comment by dhakehurst** [comment]
> why type of solution do I want?

like it says in the original question
- alter the path env variable used by the provider when running a command line (preferred)
- or, tell the provider the full path to the svn.exe to use,
